import {
  Product,
  Order,
  AllocationConflict,
  ReorderRecommendation,
  PickingTask,
  BottleneckReport,
  OperationalException,
  AuditLog,
  NotificationItem,
} from '../types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'PROD-001',
    sku: 'WM-OPT-BLK',
    name: 'Wireless Optical Mouse',
    category: 'Peripherals',
    warehouse: 'Main DC - Boston',
    location: 'A-12-3',
    totalQuantity: 32,
    reservedQuantity: 25,
    availableQuantity: 7, // CRITICAL LOW AVAILABLE
    damagedQuantity: 0,
    reorderLevel: 50,
    safetyStock: 20,
    supplier: 'LogiTech Direct',
    leadTimeDays: 5,
    averageDailyDemand: 12,
    unitPrice: 29.99,
    status: 'Low Stock',
  },
  {
    id: 'PROD-002',
    sku: 'KB-MECH-RGB',
    name: 'Mechanical RGB Keyboard',
    category: 'Peripherals',
    warehouse: 'Main DC - Boston',
    location: 'A-14-1',
    totalQuantity: 120,
    reservedQuantity: 40,
    availableQuantity: 80,
    damagedQuantity: 0,
    reorderLevel: 30,
    safetyStock: 15,
    supplier: 'Keychron Corp',
    leadTimeDays: 7,
    averageDailyDemand: 8,
    unitPrice: 89.99,
    status: 'Healthy',
  },
  {
    id: 'PROD-003',
    sku: 'MON-4K-27',
    name: '27-inch 4K UltraHD Monitor',
    category: 'Displays',
    warehouse: 'Main DC - Boston',
    location: 'B-04-2',
    totalQuantity: 15,
    reservedQuantity: 12,
    availableQuantity: 3,
    damagedQuantity: 0,
    reorderLevel: 25,
    safetyStock: 10,
    supplier: 'Dell Enterprise',
    leadTimeDays: 6,
    averageDailyDemand: 5,
    unitPrice: 349.99,
    status: 'Critical',
  },
  {
    id: 'PROD-004',
    sku: 'HDST-NC-PRO',
    name: 'Noise Cancelling Pro Headset',
    category: 'Audio',
    warehouse: 'West Coast Hub',
    location: 'C-08-4',
    totalQuantity: 0,
    reservedQuantity: 0,
    availableQuantity: 0,
    damagedQuantity: 2,
    reorderLevel: 40,
    safetyStock: 15,
    supplier: 'Sennheiser B2B',
    leadTimeDays: 4,
    averageDailyDemand: 10,
    unitPrice: 149.99,
    status: 'Out of Stock',
  },
  {
    id: 'PROD-005',
    sku: 'USB-C-HUB-8',
    name: '8-in-1 USB-C Multiport Hub',
    category: 'Accessories',
    warehouse: 'Main DC - Boston',
    location: 'A-02-5',
    totalQuantity: 210,
    reservedQuantity: 50,
    availableQuantity: 160,
    damagedQuantity: 0,
    reorderLevel: 40,
    safetyStock: 20,
    supplier: 'Anker Tech',
    leadTimeDays: 3,
    averageDailyDemand: 15,
    unitPrice: 45.00,
    status: 'Healthy',
  },
  {
    id: 'PROD-006',
    sku: 'DESK-MAT-XL',
    name: 'XL Waterproof Desk Mat',
    category: 'Accessories',
    warehouse: 'Main DC - Boston',
    location: 'A-05-1',
    totalQuantity: 95,
    reservedQuantity: 10,
    availableQuantity: 85,
    damagedQuantity: 0,
    reorderLevel: 20,
    safetyStock: 10,
    supplier: 'OrbitKey Supply',
    leadTimeDays: 5,
    averageDailyDemand: 6,
    unitPrice: 24.99,
    status: 'Healthy',
  },
  {
    id: 'PROD-007',
    sku: 'SSD-NVME-1TB',
    name: '1TB NVMe M.2 SSD Enterprise',
    category: 'Components',
    warehouse: 'Main DC - Boston',
    location: 'B-12-1',
    totalQuantity: 65,
    reservedQuantity: 30,
    availableQuantity: 35,
    damagedQuantity: 0,
    reorderLevel: 30,
    safetyStock: 15,
    supplier: 'Samsung Electronics',
    leadTimeDays: 4,
    averageDailyDemand: 9,
    unitPrice: 119.99,
    status: 'Healthy',
  },
  {
    id: 'PROD-008',
    sku: 'CABLE-HDMI-21',
    name: 'Ultra High Speed HDMI 2.1 Cable 6ft',
    category: 'Cables',
    warehouse: 'West Coast Hub',
    location: 'C-01-2',
    totalQuantity: 400,
    reservedQuantity: 100,
    availableQuantity: 300,
    damagedQuantity: 0,
    reorderLevel: 80,
    safetyStock: 40,
    supplier: 'Belkin Direct',
    leadTimeDays: 2,
    averageDailyDemand: 25,
    unitPrice: 14.99,
    status: 'Healthy',
  },
  {
    id: 'PROD-009',
    sku: 'CHAIR-ERG-BL',
    name: 'Ergonomic Mesh Office Chair',
    category: 'Furniture',
    warehouse: 'South Hub - Dallas',
    location: 'D-01-1',
    totalQuantity: 18,
    reservedQuantity: 14,
    availableQuantity: 4,
    damagedQuantity: 1,
    reorderLevel: 15,
    safetyStock: 5,
    supplier: 'Herman Miller B2B',
    leadTimeDays: 10,
    averageDailyDemand: 3,
    unitPrice: 499.00,
    status: 'Low Stock',
  },
  {
    id: 'PROD-010',
    sku: 'CAM-4K-STREAM',
    name: '4K Webcam with AI Auto-Framing',
    category: 'Displays',
    warehouse: 'Main DC - Boston',
    location: 'A-08-2',
    totalQuantity: 42,
    reservedQuantity: 20,
    availableQuantity: 22,
    damagedQuantity: 0,
    reorderLevel: 25,
    safetyStock: 10,
    supplier: 'LogiTech Direct',
    leadTimeDays: 5,
    averageDailyDemand: 6,
    unitPrice: 129.99,
    status: 'Healthy',
  },
];

// Helper to generate 40 more mock products to reach 50+ total
const ADDITIONAL_CATEGORIES = ['Peripherals', 'Displays', 'Audio', 'Components', 'Cables', 'Packaging', 'Safety Gear'];
const SUPPLIERS = ['TechGlobal', 'Nexus Supply', 'Prime Warehouse', 'Vanguard Logistics', 'Apex Components'];
const WAREHOUSES = ['Main DC - Boston', 'West Coast Hub', 'South Hub - Dallas'];

for (let i = 11; i <= 52; i++) {
  const cat = ADDITIONAL_CATEGORIES[i % ADDITIONAL_CATEGORIES.length];
  const wh = WAREHOUSES[i % WAREHOUSES.length];
  const sup = SUPPLIERS[i % SUPPLIERS.length];
  const total = Math.floor(Math.random() * 150) + 10;
  const reserved = Math.floor(total * 0.4);
  const damaged = i % 13 === 0 ? 2 : 0;
  const avail = Math.max(0, total - reserved - damaged);
  const reorder = Math.floor(total * 0.3) + 10;

  let status: Product['status'] = 'Healthy';
  if (avail === 0) status = 'Out of Stock';
  else if (avail < 10) status = 'Critical';
  else if (avail < reorder) status = 'Low Stock';
  if (damaged > 0) status = 'Damaged';

  INITIAL_PRODUCTS.push({
    id: `PROD-${String(i).padStart(3, '0')}`,
    sku: `SKU-${cat.substring(0, 3).toUpperCase()}-${100 + i}`,
    name: `${cat} Module Item #${i}`,
    category: cat,
    warehouse: wh,
    location: `${String.fromCharCode(65 + (i % 4))}-${(i % 10) + 1}-${(i % 5) + 1}`,
    totalQuantity: total,
    reservedQuantity: reserved,
    availableQuantity: avail,
    damagedQuantity: damaged,
    reorderLevel: reorder,
    safetyStock: Math.floor(reorder / 2),
    supplier: sup,
    leadTimeDays: (i % 7) + 2,
    averageDailyDemand: (i % 12) + 2,
    unitPrice: parseFloat((Math.random() * 120 + 15).toFixed(2)),
    status,
  });
}

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-1042',
    customerName: 'Acme Global Enterprises',
    customerTier: 'Enterprise',
    items: [
      {
        productId: 'PROD-001',
        sku: 'WM-OPT-BLK',
        productName: 'Wireless Optical Mouse',
        quantityRequested: 10,
        quantityAllocated: 0,
        unitPrice: 29.99,
      },
      {
        productId: 'PROD-002',
        sku: 'KB-MECH-RGB',
        productName: 'Mechanical RGB Keyboard',
        quantityRequested: 5,
        quantityAllocated: 5,
        unitPrice: 89.99,
      },
    ],
    totalValue: 749.85,
    createdTime: '2026-08-18T08:15:00',
    dispatchDeadline: '2026-08-18T11:45:00', // 50 mins from now
    priority: 'Critical',
    priorityScore: 94,
    priorityReasons: [
      'Dispatch deadline in under 1 hour (Urgency Score: +40)',
      'Enterprise customer tier SLA agreement (+25)',
      'High order value ($749.85) (+15)',
      'Order age > 2.5 hours (+14)',
    ],
    priorityBreakdown: {
      deadlineUrgencyScore: 40,
      slaRiskScore: 25,
      customerTierScore: 20,
      inventoryReadinessScore: 9,
      orderAgeScore: 14,
    },
    status: 'Pending Allocation',
    riskLevel: 'High Risk',
    allocatedZone: 'Zone B',
  },
  {
    id: 'ORD-1047',
    customerName: 'Nexus Tech Logistics',
    customerTier: 'VIP',
    items: [
      {
        productId: 'PROD-001',
        sku: 'WM-OPT-BLK',
        productName: 'Wireless Optical Mouse',
        quantityRequested: 5,
        quantityAllocated: 0,
        unitPrice: 29.99,
      },
      {
        productId: 'PROD-005',
        sku: 'USB-C-HUB-8',
        productName: '8-in-1 USB-C Multiport Hub',
        quantityRequested: 2,
        quantityAllocated: 2,
        unitPrice: 45.00,
      },
    ],
    totalValue: 239.95,
    createdTime: '2026-08-18T09:30:00',
    dispatchDeadline: '2026-08-18T16:00:00',
    priority: 'Medium',
    priorityScore: 62,
    priorityReasons: [
      'Dispatch deadline > 5 hours away',
      'VIP Tier customer account',
      'Moderate order value ($239.95)',
    ],
    priorityBreakdown: {
      deadlineUrgencyScore: 15,
      slaRiskScore: 15,
      customerTierScore: 15,
      inventoryReadinessScore: 10,
      orderAgeScore: 7,
    },
    status: 'Pending Allocation',
    riskLevel: 'On Track',
    allocatedZone: 'Zone B',
  },
  {
    id: 'ORD-1039',
    customerName: 'Starlight Retailers',
    customerTier: 'Standard',
    items: [
      {
        productId: 'PROD-003',
        sku: 'MON-4K-27',
        productName: '27-inch 4K UltraHD Monitor',
        quantityRequested: 2,
        quantityAllocated: 2,
        unitPrice: 349.99,
      },
    ],
    totalValue: 699.98,
    createdTime: '2026-08-18T07:00:00',
    dispatchDeadline: '2026-08-18T12:00:00',
    priority: 'High',
    priorityScore: 81,
    priorityReasons: [
      'Dispatch deadline in 1 hour',
      'Order allocated and ready for picking',
    ],
    priorityBreakdown: {
      deadlineUrgencyScore: 35,
      slaRiskScore: 20,
      customerTierScore: 10,
      inventoryReadinessScore: 10,
      orderAgeScore: 6,
    },
    status: 'Picking',
    riskLevel: 'Medium Risk',
    allocatedZone: 'Zone B',
    assignedPicker: 'Dave Miller',
  },
  {
    id: 'ORD-1035',
    customerName: 'OmniCorp Solutions',
    customerTier: 'Enterprise',
    items: [
      {
        productId: 'PROD-007',
        sku: 'SSD-NVME-1TB',
        productName: '1TB NVMe M.2 SSD Enterprise',
        quantityRequested: 4,
        quantityAllocated: 4,
        unitPrice: 119.99,
      },
    ],
    totalValue: 479.96,
    createdTime: '2026-08-18T06:30:00',
    dispatchDeadline: '2026-08-18T13:00:00',
    priority: 'High',
    priorityScore: 78,
    priorityReasons: ['Enterprise customer SLA', 'Items picked & at packing station'],
    priorityBreakdown: {
      deadlineUrgencyScore: 25,
      slaRiskScore: 25,
      customerTierScore: 20,
      inventoryReadinessScore: 5,
      orderAgeScore: 3,
    },
    status: 'Packed',
    riskLevel: 'On Track',
    allocatedZone: 'Zone A',
  },
  {
    id: 'ORD-1031',
    customerName: 'Horizon Dynamics',
    customerTier: 'VIP',
    items: [
      {
        productId: 'PROD-002',
        sku: 'KB-MECH-RGB',
        productName: 'Mechanical RGB Keyboard',
        quantityRequested: 10,
        quantityAllocated: 10,
        unitPrice: 89.99,
      },
    ],
    totalValue: 899.90,
    createdTime: '2026-08-18T05:00:00',
    dispatchDeadline: '2026-08-18T11:30:00',
    priority: 'Critical',
    priorityScore: 91,
    priorityReasons: ['QC Inspection pending', 'Dispatch in 35 mins'],
    priorityBreakdown: {
      deadlineUrgencyScore: 38,
      slaRiskScore: 25,
      customerTierScore: 18,
      inventoryReadinessScore: 5,
      orderAgeScore: 5,
    },
    status: 'Quality Check',
    riskLevel: 'High Risk',
    allocatedZone: 'Zone C',
  },
  {
    id: 'ORD-1028',
    customerName: 'Apex Systems',
    customerTier: 'Standard',
    items: [
      {
        productId: 'PROD-005',
        sku: 'USB-C-HUB-8',
        productName: '8-in-1 USB-C Multiport Hub',
        quantityRequested: 15,
        quantityAllocated: 15,
        unitPrice: 45.00,
      },
    ],
    totalValue: 675.00,
    createdTime: '2026-08-18T04:00:00',
    dispatchDeadline: '2026-08-18T14:00:00',
    priority: 'Medium',
    priorityScore: 55,
    priorityReasons: ['Passed QC', 'Ready for Dispatch'],
    priorityBreakdown: {
      deadlineUrgencyScore: 15,
      slaRiskScore: 10,
      customerTierScore: 10,
      inventoryReadinessScore: 10,
      orderAgeScore: 10,
    },
    status: 'Ready for Dispatch',
    riskLevel: 'On Track',
    allocatedZone: 'Zone A',
  },
];

export const INITIAL_CONFLICTS: AllocationConflict[] = [
  {
    id: 'CONF-001',
    productId: 'PROD-001',
    productName: 'Wireless Optical Mouse (SKU: WM-OPT-BLK)',
    totalAvailable: 7,
    demandingOrders: [
      {
        orderId: 'ORD-1042',
        customerName: 'Acme Global (Enterprise)',
        requestedQty: 10,
        priority: 'Critical',
        priorityScore: 94,
        dispatchDeadline: '11:45 AM (50 mins left)',
      },
      {
        orderId: 'ORD-1047',
        customerName: 'Nexus Tech (VIP)',
        requestedQty: 5,
        priority: 'Medium',
        priorityScore: 62,
        dispatchDeadline: '04:00 PM (5 hours left)',
      },
    ],
    recommendedDecision: {
      orderAllocations: {
        'ORD-1042': 7, // Give all 7 to critical order
        'ORD-1047': 0, // 0 to medium order
      },
      explanation:
        'Order #1042 has CRITICAL priority (score 94 vs 62) with a dispatch deadline expiring in 50 minutes. Allocating all 7 available units to Order #1042 fulfills 70% of its order and avoids high-tier SLA penalty.',
      impact: 'Prevents $5,000 SLA penalty for Acme Global. Order #1047 deferred without SLA impact.',
    },
    status: 'Pending Review',
  },
];

export const INITIAL_REORDERS: ReorderRecommendation[] = [
  {
    id: 'REORD-001',
    productId: 'PROD-001',
    productName: 'Wireless Optical Mouse',
    sku: 'WM-OPT-BLK',
    currentStock: 25,
    averageDailyDemand: 12,
    leadTimeDays: 5,
    safetyStock: 20,
    expectedRequirement: 80, // (12 * 5) + 20
    recommendedOrderQty: 75,
    reason: 'Demand during lead time (60 units) + Safety stock (20 units) - Available stock (25 units) = 55 deficit + batch safety buffer.',
    status: 'Recommended',
  },
  {
    id: 'REORD-002',
    productId: 'PROD-003',
    productName: '27-inch 4K UltraHD Monitor',
    sku: 'MON-4K-27',
    currentStock: 15,
    averageDailyDemand: 5,
    leadTimeDays: 6,
    safetyStock: 10,
    expectedRequirement: 40,
    recommendedOrderQty: 30,
    reason: 'High demand surge; 3 units available remaining after reservations.',
    status: 'Recommended',
  },
];

export const INITIAL_PICKING_TASKS: PickingTask[] = [
  {
    id: 'PICK-101',
    orderId: 'ORD-1039',
    pickerName: 'Dave Miller (Zone B)',
    zone: 'Zone B',
    items: [
      { productId: 'PROD-001', productName: 'Wireless Mouse', location: 'A1', quantity: 2, picked: true },
      { productId: 'PROD-002', productName: 'RGB Keyboard', location: 'A5', quantity: 1, picked: true },
      { productId: 'PROD-003', productName: '4K Monitor', location: 'B2', quantity: 2, picked: false },
      { productId: 'PROD-005', productName: 'USB-C Hub', location: 'B7', quantity: 1, picked: false },
      { productId: 'PROD-007', productName: 'NVMe SSD', location: 'C3', quantity: 4, picked: false },
    ],
    unoptimizedSequence: ['A1', 'C3', 'B7', 'A5', 'B2'],
    routeSequence: ['A1', 'A5', 'B2', 'B7', 'C3'],
    estimatedTimeMin: 18.5,
    optimizedTimeMin: 11.2,
    status: 'Picking',
  },
];

export const INITIAL_BOTTLENECK_REPORTS: BottleneckReport[] = [
  {
    zone: 'Zone B (Peripherals & Displays)',
    averagePickTimeMin: 18.4,
    warehouseAverageMin: 11.1,
    delayedOrdersCount: 32,
    errorRatePercent: 4.8,
    recommendation: 'CRITICAL BOTTLENECK: Zone B picking time is 65% slower than warehouse average due to high aisle congestion and item spacing. Reassign 2 pickers from Zone A to Zone B immediately.',
    assignedWorkers: 3,
  },
  {
    zone: 'Zone A (Fast-Moving Tech Accessories)',
    averagePickTimeMin: 9.2,
    warehouseAverageMin: 11.1,
    delayedOrdersCount: 2,
    errorRatePercent: 0.9,
    recommendation: 'Optimal performance. Zone A has 4 active pickers operating at 120% target efficiency.',
    assignedWorkers: 4,
  },
  {
    zone: 'Zone C (Components & High Density)',
    averagePickTimeMin: 12.0,
    warehouseAverageMin: 11.1,
    delayedOrdersCount: 5,
    errorRatePercent: 1.5,
    recommendation: 'Normal load. Minor congestion during peak 10:00-11:00 AM window.',
    assignedWorkers: 3,
  },
];

export const INITIAL_EXCEPTIONS: OperationalException[] = [
  {
    id: 'EX-1042',
    type: 'Quantity Mismatch',
    severity: 'Critical',
    orderId: 'ORD-1031',
    productId: 'PROD-002',
    detectedTime: '2026-08-18 10:14 AM',
    problemDescription: 'QC Station #3 reported quantity mismatch for Order #1031. Expected: 10 units, Found in Bin: 9 units.',
    dataConsidered: 'Order #1031 line items, Pick List PICK-099 log, Zone C inventory bin C-14 stock reading.',
    aiDecision: 'Dispatch secondary pick runner to Zone C Bin C-14 to fetch 1 remaining unit immediately.',
    reasoning: 'Product PROD-002 has 80 available units in stock. Fetching 1 unit resolves the order without re-packing overhead.',
    suggestedAction: 'Approve rapid replenishment runner pick.',
    expectedImpact: 'Prevents dispatch delay for Order #1031 (Critical SLA deadline 11:30 AM).',
    status: 'Open',
  },
  {
    id: 'EX-1038',
    type: 'Damaged Item',
    severity: 'Warning',
    orderId: 'ORD-1035',
    productId: 'PROD-004',
    detectedTime: '2026-08-18 09:20 AM',
    problemDescription: 'Noise Cancelling Headset box torn during picking transport.',
    dataConsidered: 'Operator inspection report, Damaged stock log.',
    aiDecision: 'Mark 1 unit as Damaged. Allocate 1 replacement unit from West Coast Hub reserve.',
    reasoning: 'Damaged stock must be isolated to avoid customer return.',
    suggestedAction: 'Transfer unit to Damaged Quarantine bin D-99.',
    expectedImpact: 'Maintains 100% quality rating on customer delivery.',
    status: 'Resolved',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'AUD-9001',
    timestamp: '2026-08-18 10:15 AM',
    event: 'Smart Priority Calculation',
    orderId: 'ORD-1042',
    decision: 'Priority calculated as CRITICAL (Score: 94)',
    reason: 'Dispatch deadline in 50 minutes + Enterprise Tier SLA customer.',
    performedBy: 'AI Decision Engine',
    approvedBy: 'System Auto-Engine',
  },
  {
    id: 'AUD-9002',
    timestamp: '2026-08-18 10:20 AM',
    event: 'Inventory Allocation Conflict Detected',
    orderId: 'ORD-1042',
    decision: 'Flagged contention between ORD-1042 and ORD-1047 for PROD-001',
    reason: 'Requested total (15 units) exceeds available stock (7 units).',
    performedBy: 'Smart Allocation Engine',
  },
  {
    id: 'AUD-9003',
    timestamp: '2026-08-18 10:30 AM',
    event: 'Route Optimization Applied',
    orderId: 'ORD-1039',
    decision: 'Optimized picking route sequence from 18.5 min to 11.2 min',
    reason: 'Re-sequenced aisle path A1->A5->B2->B7->C3 reducing travel distance by 40%.',
    performedBy: 'Picking Path Optimizer',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NOTIF-1',
    type: 'Critical Order',
    severity: 'Critical',
    title: 'High SLA Risk Alert',
    message: 'Order #1042 (Acme Global) is at risk of missing dispatch deadline in 50 mins.',
    timestamp: '10 min ago',
    read: false,
    actionUrl: '/orders/ORD-1042',
  },
  {
    id: 'NOTIF-2',
    type: 'Allocation Conflict',
    severity: 'Critical',
    title: 'Inventory Allocation Conflict',
    message: 'Wireless Optical Mouse stock (7 avail) requested by 2 orders. Recommendation ready.',
    timestamp: '15 min ago',
    read: false,
    actionUrl: '/allocation',
  },
  {
    id: 'NOTIF-3',
    type: 'Bottleneck',
    severity: 'Warning',
    title: 'Picking Zone B Bottleneck',
    message: 'Zone B pick time (18.4 min) is 65% above warehouse average.',
    timestamp: '30 min ago',
    read: false,
    actionUrl: '/picking',
  },
];
